### ISSUE TITLE
This looks like Windows XP and that makes me sad

### ISSUE THREAD

**Issue by mjchamplin** [octalmage/Notepad#4]
Yeah that's right, I consider this an issue.

**Comment by octalmage** [comment]
Haha! I spent a lot of time making it look like XP. Which Windows version would you prefer?

**Comment by mjchamplin** [comment]
I'm just messing with you. It's just been a while since I've opened a window to that shiny rounded-corners glowing blue experience, that's all. ;)

**Comment by mjchamplin** [comment]
![](http://www.guidebookgallery.org/pics/gui/applications/office/notepad/win31.png)

**Comment by octalmage** [comment]
Oh snap, this could be a series! 

It's pretty freaky seeing the XP window on Mac right? I've been using it as a scratchpad.

**Comment by mjchamplin** [comment]
Yeah it's jarring!

**Comment by mjchamplin** [comment]
Actually, if I wanted to fork this to skin it myself, how would I run the source? (n00b)

**Comment by octalmage** [comment]
Install nw.js:

```
npm install nw -g
```

Then run:

```
nw ./
```

In the root of your fork!

**Comment by mjchamplin** [comment]
Kickass! Thanks dude.

**Comment by octalmage** [comment]
No problem! Im off to preserve more history!
